apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-drsj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bvit-tenant/rhtap-demo-app/hacbs-test-project-drsj@sha256:f6eadd15a574aa77a34ba1f00c82051be9b24caab37c95ff23514a1e043a4980
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
