apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-drsj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bvit-tenant/rhtap-demo-app/hacbs-test-project-drsj@sha256:eb5be367dd585f6294b8d24177b38b7012e94aaa34c4c1c558b6eea1b5c2adf3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
